### ISSUE TITLE
Activate/deactivate states except for one

### ISSUE THREAD

**Issue by bm480** [eriks5/org.scheffers.homey.sets#1]
To make sets work more like a regular state machine, a feature that allows activating a single state (while deactivating other states) would come in handy. Maybe add a checkbox to the activate/deactivate action Flowcards that enables the option to deactivate/activate other states automatically.

**Comment by bm480** [comment]
State machines should be implemented using the State Control app, but this might still be a nice addition to the featureset. For example to implement states that can override other states, e.g. manually switch a light overrides multiple automatic triggers.

**Comment by eriks5** [comment]
Implemented in https://github.com/eriks5/org.scheffers.homey.sets/commit/411286b6ebfdcde4406d315c6debb2d8c4b68b61

**Comment by bm480** [comment]
Only last weekend I had a chance to test this. Works like a charm!
