### ISSUE TITLE
States are not createable in Homey v2.0.0-rc9

### ISSUE THREAD

**Issue by ma-be** [eriks5/org.scheffers.homey.sets#10]
Hi Erik,
I am giving a try to the newest firmware and I am not able to define states in the mobile app Homey v2. On the Setting page there is no GUI element to add a State to the defined Set.
I am not sure if it is an issue with your app because it is not compatible with the new firmware or it is a bug of the new firmware/mobile app and should be reported to Athom...
What do you think?
Thank you,
M.

**Comment by eriks5** [comment]
Most likely an issue in this app. I haven't dared to install v2 yet (my setup depends on a few apps that aren't compatible yet), so I couldn't test this app on v2 yet.

The settings page uses javascript libraries used by Homey itself for the desktop client. Since that has been axed, those libraries are probably gone too. I hope I will be able to look into this soon, but worst case it will require a complete rewrite of the settings page that might take me some time.

**Comment by eriks5** [comment]
Just upgraded my Homey to v2.0.0-rc11 and tested the app. Although not very user-friendly, the settings do seem to work almost completely, but the areas where to touch the buttons is small as it was designed for use with a mouse.

The only thing that does not seem to work is toggling states, but that is also the least important feature of the settings page as you only use that for testing your sets. Adding and removing sets and states works for me.

Will look into rebuilding the settings to be mobile first soon.

**Comment by ma-be** [comment]
Thank you for your response.
For me, it does not work in current situation. 
I do not see any touch button for State definition/change in the iOS app (Homey Gen 2). I attach a screenshot.
Looking forward for you update :-)

![img_8601](https://user-images.githubusercontent.com/11045804/50859788-9789f880-1394-11e9-8cc7-862deaa84ba1.PNG)

**Comment by eriks5** [comment]
I'm using Android, probably why it works different.

Just submitted a beta version (0.4.0) with a reworked settings page to the Homey app store. Once it's approved you can install it. Let me know how it looks on iOS

**Comment by ma-be** [comment]
Beta (v0.4.0) works perfect with iOS.
I am attaching a screenshot.
Thank you.
![img_8629](https://user-images.githubusercontent.com/11045804/51136730-7f572500-183d-11e9-8c6a-4b408e1840f6.PNG)
