### ISSUE TITLE
Possibility to read out sets info

### ISSUE THREAD

**Issue by Gammelgreggan** [eriks5/org.scheffers.homey.sets#11]
Hi!
It would be nice to be able to read out the sets state info, to be used e.g. in an email.
I use your Sets to check my sensors. Every sensor has it own state and activates it when reporting e.g. motion or door open. The I regularily check the set if all states has been activated since last check. If not I send myself an email, and it would be nice to be able to show the states state.

/Anders

**Comment by eriks5** [comment]
Homey's API lets you to access this already. Try this at the API playground at https://developer.athom.com/tools/api-playground on a Homey that has the app installed:

```
Homey.apps.getAppSettings({id:'org.scheffers.homey.sets'});
```
