### ISSUE TITLE
My bad: I can't get it working

### ISSUE THREAD

**Issue by FreekBos** [eriks5/org.scheffers.homey.sets#12]
Hi Erik,
I must be overlooking something but I can't get it to work. I know I "need" it in my configuration so I'm trying to get 2 xoaimi sensors in a set. 
I'm trying in "configure app" to create 1 "bg_sensor" (nieuwe verzameling) and hit the checkmark.
The next interface tells me "voeg toestanden aan de verzameling to om deze te kunnen gebruiken". I enter "Present" and "Noone" as these are my 2 states.
What to do next? Maybe just a bit of documentation to help the poor souls on their way ;-)
Thankss a mil

**Comment by eriks5** [comment]
GitHub is not a support forum, use the Homey forum for that. But the short answer is: create flows that act upon changes in your sensors and updates the states. This is already documented in the README: "Using the settings page, sets and states are created. After that, these sets and states are available to be used in flows."
