### ISSUE TITLE
Activate a state only when a certain amount of time has passed

### ISSUE THREAD

**Issue by bm480** [eriks5/org.scheffers.homey.sets#2]
This feature comes in handy when acting on value changes, for example when monitoring a washing machine you only want to change the state when the energy levels are low for at least a minimum amount of time.

Trigger a state with a timeout, but the state should only actually be activated after the timeout has expired. If before that happens, the state is triggered another time (either immediately or using another timeout) the timeout should be cancelled. Optionally, except for the triggered state other states should be deactivated at the same time.

**Comment by eriks5** [comment]
You can currently already activate a state temporarily and then automatically have it deactivated. I think that would cover this use case as well, just invert what you want to do.

In your example, set a temporary state with a timeout each time the energy level is high, when the state is deactivated it's been low for the set timeout.

**Comment by bm480** [comment]
It's tempting but I don't think this is possible right now. Let me eleborate on this a bit more.

Currently I have 4 states for my washing machine. First state is OFF and the energy level is below the L0 threshold. When the machine is turned on, the level is between L0 and L1 which causes the STANDBYE state to become active. After starting the washing program, the level will be above threshold L1 and WASHING state becomes active. However, during the washing program energy levels regularly drop below L1 and only if it is below L1 for more than x minutes we can conclude that the program has finished and we can enter state DONE. That is why I suggested the feature of activating a state only after a timeout has been reached.

I don't see how to implement this with existing Sets-functionality. Am I missing something?

At this moment I use the States and Countdown apps to start a timer when energy levels are below the threshold and trigger a state change when the timer completes. The timer is reset when energy levels go above the threshold again. There are some drawbacks in using States (which can get complex) and Countdown, I'd like to replace these with Sets.

**Comment by eriks5** [comment]
Right now, this isn't the right app for this. The 'statecontrol' app you're already using is the correct way to do it. 

This app is about aggregating multiple binary states into one. 

Further discussion should be in the forum, not on GitHub.

**Comment by bm480** [comment]
Yes, I agree.

**Comment by eriks5** [comment]
Reopening, the requested feature itself is useful and shouldn't be too hard to implement.

**Comment by eriks5** [comment]
Implemented in https://github.com/eriks5/org.scheffers.homey.sets/commit/fa769dcd28567a527bb3665d9117d1978dc95d70

**Comment by bm480** [comment]
Only last weekend I had a chance to test this. Works like a charm!
