### ISSUE TITLE
[Feature request] Ordered sets: test if a state is active while no states above are active

### ISSUE THREAD

**Issue by bm480** [eriks5/org.scheffers.homey.sets#5]
This is my use case: currently I find it difficult if not impossible to do this with existing Homey functionality. I want the LED Ring to represent one of the states that are currently active. However, I want this to be deterministic. 

For example when my washing machine and tumble dryer are both ready the LED Ring should indicate one of these situations by flashing green. However, if its going to rain outside the LED Ring should flash blue. Of course, the LED Ring can only show one of these at a time. With sets upon a status change I could check for a status indicating washing machine ready and then make the LED Ring flash green. At the same time I could check for a status indicating its going to rain, but since the washing machine is also active the check should fail. Then, when the status for the washing machine is changed to inactive the status for rain would succeed and the LED Ring can be made blue.

I think this would require only minor change in the implementation of sets. Being able to (re)order states would be nice, but if we could assume alfabetic order that would be sufficient.

**Comment by eriks5** [comment]
You can do this with conditions. One flow for each led-ring color. Trigger the flow on any change in the set, and have conditions like "washing machine set" and "rain not set", and an action to change the color.

**Comment by bm480** [comment]
Thanks, works like a charm! But the number of conditions in every flow increase with increasing numbers of led-ring color notifications. For now I manage, but this might get more complex than needed in the future. In that case, the suggested Sets-feature could improve flow managability.
