### ISSUE TITLE
Empty State being created at times

### ISSUE THREAD

**Issue by bm480** [eriks5/org.scheffers.homey.sets#7]
I have a set containing the following states:

Brandalarm
Inbraakalarm
Regen
Wasdroger klaar
Wasmachine klaar
Waterkoker klaar

A state is Activated to trigger audio and visual signaling. Whenever a state is Deactivated several flows detect which signaling should be displayed by the LED Ring. I only use actions "Activate state", "Deactivate state", triggers "States changed", "No states active" and conditions "State is active", "State is inactive". 

Sometimes I notice that an empty State is being added to the six states already existing. I know that States are being recreated automatically, but I've checked all flows I can think of where the Set is being referenced, but didn't find a reference with an invalid and/or empty State. Also, I'm unable to add a state without a name manually using the Sets editor which makes me think something must be wrong in the app.

**Comment by eriks5** [comment]
Which version of the app do you use? There is a stable (0.3.0) and a beta (0.3.1) version in the app store. The beta version is for homey firmware 1.5

**Comment by bm480** [comment]
This is in the stable version 0.3.0. I must note that yesterday I've rewritten the rules for my Washing machine ready indicator and have not seen this behaviour yet so it might be difficult to reproduce.

**Comment by bm480** [comment]
Yesterday, Sets upgraded to 0.3.1 so I will be closely watching if the issue happens again.

**Comment by eriks5** [comment]
v0.3.2 was just accepted to the app store that should fix this
