### ISSUE TITLE
card AND column

### ISSUE THREAD

**Issue by yemoH** [eriks5/org.scheffers.homey.sets#8]
For a couple of weeks I'm using the SETS app in Homey. My set up works with three motion detectors. 
In the WHEN column there is a card 'some states active', but this card 'some states active' is not available in the AND column. Maybe I overlook something but since I don't know which motion detectors is active, I think a card 'some states active' in AND column would be very helpful.  
Thank you for your help.

**Comment by yemoH** [comment]
Oops, I found the card 'states active' by checking the checkbox. I think that is what I'm looking. 
I'm sorry for bother you.

**Comment by eriks5** [comment]
Yes, that is the card that you'd want for this.
